In [1]:
print("hello world")

hello world


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
list =["pride",10,20,3.14]

In [4]:
print(list)

['pride', 10, 20, 3.14]


In [5]:
arr =np.array(list)
print(arr)

['pride' '10' '20' '3.14']


In [6]:
list1 =[10,20,30,43]

In [7]:
arr =np.array(list1)
print(arr)

[10 20 30 43]


In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(4,)

In [10]:
list2=[[1,2,3],[7,8,9],[11,12,13]]
arr=np.array(list2)
print(arr)

[[ 1  2  3]
 [ 7  8  9]
 [11 12 13]]


In [11]:
arr.shape

(3, 3)

In [12]:
arr[1][2]

np.int64(9)

In [13]:
arr[2][2]

np.int64(13)

In [14]:
arr.reshape(9,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 7],
       [ 8],
       [ 9],
       [11],
       [12],
       [13]])

In [15]:
arr.reshape(1,9)

array([[ 1,  2,  3,  7,  8,  9, 11, 12, 13]])

In [16]:
lst=[[1,2,3,4],[4,5,6,7],[7,8,9,10]]
arr=np.array(lst)
print(arr)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [17]:
#Indexing in Numpy - Arrays
arr[2]

array([ 7,  8,  9, 10])

In [18]:
arr[0:,:]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [19]:
arr[:2,1:3]

array([[2, 3],
       [5, 6]])

In [20]:
arr[:-2,-1:-3]

array([], shape=(1, 0), dtype=int64)

In [21]:
arr[-2:,-3:-1]

array([[5, 6],
       [8, 9]])

In [22]:
arr[-2:,-2:0]

array([], shape=(2, 0), dtype=int64)

In [23]:
arr[-2:,-1:]

array([[ 7],
       [10]])

In [24]:
np.arange

<function numpy.arange>

In [25]:
array1=np.random.randint(0,100, 5)
print(array1)

[ 0  4 89 23 94]


In [26]:
array2=np.random.randint(-200,-100, 5)
print(array2)

[-121 -104 -107 -111 -156]


In [27]:
np.concatenate([array1,array2]).reshape(2,5)

array([[   0,    4,   89,   23,   94],
       [-121, -104, -107, -111, -156]], dtype=int32)